### ISSUE TITLE
Публікується чернетка

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_telegram#13]
1. створюємо звіт, зберігаємо коротеньку чернетку
2. відкриваємо цю чернетку і пишемо нормальний повний звіт
3. публікуємо
4. в телеграм каналі публікується чернетка

Приклад: https://t.me/rivnefish/3426

**Comment by chyvonomys** [comment]
боту на /publish посилають json виду {'id': NNN}, бот іде на апі витягує цей звіт NNN і публікує його в канал. він нічого сам не видумує а просто постить в канал те що вернуло апі.
