### ISSUE TITLE
Змінити набір водойм на вибір

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_telegram#5]
Коли запускаєш бота без введення жодного символу, то він видає останні додані водойми в базу.
Потрібно в тому списку видавати найкращі водойми нашого сервісу, щоб люди полюбили рівнефіш з першого запуску!

Тут може бути кілька варіантів:
1. видавати список найпопулярніших водойм(де найбільше звітів)
2. видавати список водойм з найбільшим рейтингом
3. самим формувати цей список <- мені найбільше це імпонує

**Comment by chyvonomys** [comment]
варіант 3 можна зробити наступним чином: у сервера бота буде URL наприклад `/set_top` на який можна бути постити список айдішок наприклад у форматі JSON:
```
POST https://localhost:<port>/set_top
Content-Type: application/json

{
    "ids": [20, 21, 800]
}
```

по дефолту топ пустий, в рантаймі можна міняти топ без перезапуску процеса бота.

це типу як зараз із `/reload_places`

**Comment by stal1n274** [comment]
На даний момент я не проти варіанту з ручним наповненням топу

В майбутньому волів би бачити новий метод нашого API який буде повертати ТОП10 водойм

**Comment by chyvonomys** [comment]
збєцано. приклад використання і відповідні логи:
```
# curl http://localhost:2359/reload_places
# curl -H "Content-Type: application/json" -X POST -d '{"ids": [20,21,23]}' http://localhost:2359/set_top
```
```
2017-06-13 17:56:15 INFO [rvfish_bot::fish] fetched 840 places
2017-06-13 17:56:15 INFO [rvfish_bot] reloaded place list and invalidated cache
2017-06-13 17:56:22 INFO [rvfish_bot] updated top fishing places with 3 items
2017-06-13 17:56:58 INFO [rvfish_bot] IQ id 233913733143492634, from user '@chyvonomys' (54462285), query: ``, took PT0.300649339S
```
УВАГА: виглядає так що телеграм кешує інлайн запроси, тому деколи треба почекати трохи шоб інвалідейтнувся цей кеш (десь хвилину)

**Comment by stal1n274** [comment]
все чітко
