### ISSUE TITLE
Не публікуються фотографії в канал, якщо воно були збережені з Вайберу

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_telegram#9]
У випадку, якщо до звіту з риболовлі додати фотографії, які були завантаженя спочатку з вайберу (десктоп клієнт на Windows), то такі фотки не публікуються в телеграм каналі.

Звіт на вебсайті: https://rivnefish.com/reports/3189/vilkhivka-01-04-2018
Звіт в телеграмі:  https://t.me/rivnefish/654
Самі фотки я вже на канал додав вручну, через десктоп-клієнт телеграму
Ось власне лог:
```2018-04-04 11:06:36 ERROR [rvfish_bot] /publish #3189: Bot API error: Some("Bad Request: group send failed")```

Ось ці фотографії: https://www.dropbox.com/sh/1upzyybpduxdytt/AAD8hl5rB9urctB8Tu_anBnga?dl=0,

**Comment by chyvonomys** [comment]
дійсно, телеграм бот апі сприймає не будь-який jpeg:

урл який сприймається (звіт 3188):
`https://rivnefish-photos.s3.eu-central-1.amazonaws.com/c9cd5-15948-photo/photo/medium-ccc268949bd660ae02ef92f1f2eef1eb.jpg`

урл який не сприймається (звіт 3189):
`https://rivnefish-photos.s3.eu-central-1.amazonaws.com/6c76b-15952-photo/photo/medium-01076a1957205bee645f13b3e1fc8981.jpg`

я не знаю в чому різниця, поверхнево:

```
lilac:rivnefish_telegram andriy$ file 3188-1.jpg 
3188-1.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1024x768, frames 3
lilac:rivnefish_telegram andriy$ file 3189-1.jpg 
3189-1.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=2, orientation=upper-left], baseline, precision 8, 576x768, frames 3
```

**Comment by stal1n274** [comment]
це все тому, що Вайбер - кончений

**Comment by ttp** [comment]
коли надсилаєш ці фото просто в чат він їх нормально сприймає і показує

**Comment by chyvonomys** [comment]
через клієнт -- так, через апі -- ні

**Comment by chyvonomys** [comment]
я думаю клієнт перед аплоадом перекодовує, ok.jpg, fail.jpg - оригінальні, ok2.jpg, fail2.jpg це ті зааплоаджені через клієнт і скачані назад, вони відрізняються від оригінальних:
```
$ file ok2.jpg
ok2.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, baseline, precision 8, 1024x768, frames 3

$ file fail2.jpg
fail2.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, baseline, precision 8, 576x768, frames 3

$ file ok.jpg
ok.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1024x768, frames 3

$ file fail.jpg
fail.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=2, orientation=upper-left], baseline, precision 8, 576x768, frames 3

$ ls -l *.jpg
-rw-r--r-- 1 ... 120695 Apr  4 11:58 fail.jpg
-rw-r--r-- 1 ... 117015 Apr  6 15:03 fail2.jpg
-rw-r--r-- 1 ... 167469 Apr  4 11:42 ok.jpg
-rw-r--r-- 1 ... 239511 Apr  6 15:03 ok2.jpg

```

**Comment by stal1n274** [comment]
це якась вайберівська мутня
